# Generated by Django 6.0.6 on 2026-07-01 10:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('credits', models.PositiveIntegerField()),
                ('price_xof', models.DecimalField(decimal_places=2, help_text='Prix en FCFA (min 200).', max_digits=10, validators=[django.core.validators.MinValueValidator(200)])),
                ('active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('order', 'price_xof'),
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SIGNUP_BONUS', "Bonus d'inscription"), ('PURCHASE', 'Achat'), ('CONSUMPTION', 'Consommation'), ('REFUND', 'Remboursement')], max_length=20)),
                ('amount', models.IntegerField(help_text='Positif = crédit, négatif = débit.')),
                ('balance_after', models.IntegerField(default=0)),
                ('fedapay_transaction_id', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('payment_status', models.CharField(choices=[('PENDING', 'En attente'), ('PAID', 'Payé'), ('FAILED', 'Échoué')], default='PAID', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='credits.creditpack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
