# Generated by Django 6.0.6 on 2026-07-01 10:58

import pgvector.django.vector
from django.db import connection, migrations, models

try:
    from pgvector.django import VectorExtension
except Exception:  # pragma: no cover
    VectorExtension = None


def _extension_ops():
    """Enable the pgvector extension on PostgreSQL only."""
    if VectorExtension is not None and connection.vendor == "postgresql":
        return [VectorExtension()]
    return []


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = _extension_ops() + [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('source', models.CharField(blank=True, max_length=500)),
                ('category', models.CharField(choices=[('FILIERES', 'Filières'), ('UNIVERSITES', 'Universités'), ('BOURSES', 'Bourses'), ('DEBOUCHES', 'Débouchés'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20)),
                ('content', models.TextField()),
                ('country_scope', models.CharField(blank=True, help_text='Pays/zone concerné, ou vide = global.', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
    ]
