# Generated by Django 6.0.6 on 2026-07-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgedocument',
            name='pdf_file',
            field=models.FileField(blank=True, help_text="PDF de référence — son texte est extrait automatiquement à l'enregistrement.", null=True, upload_to='knowledge_pdfs/'),
        ),
        migrations.AlterField(
            model_name='knowledgedocument',
            name='content',
            field=models.TextField(blank=True, help_text='Rempli automatiquement depuis le PDF, ou saisi à la main.'),
        ),
    ]
