# Generated by Django 6.0.6 on 2026-07-01 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('orientation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bac_serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='orientation.bacserie'),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_subjects',
            field=models.ManyToManyField(blank=True, related_name='fans', to='orientation.subject'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
