# Generated by Django 6.0.6 on 2026-07-01 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BacSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('order', 'code'),
            },
        ),
        migrations.CreateModel(
            name='OrientationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'En cours'), ('GENERATING', 'Génération en cours'), ('COMPLETED', 'Terminé'), ('FAILED', 'Échoué')], default='IN_PROGRESS', max_length=12)),
                ('credits_spent', models.PositiveIntegerField(default=0)),
                ('progress_message', models.CharField(blank=True, max_length=160)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrientationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_score', models.PositiveSmallIntegerField(default=0)),
                ('top_filieres', models.JSONField(blank=True, default=list)),
                ('top_universities', models.JSONField(blank=True, default=list)),
                ('career_outlooks', models.JSONField(blank=True, default=list)),
                ('average_salary', models.JSONField(blank=True, default=list)),
                ('skills_to_develop', models.JSONField(blank=True, default=list)),
                ('personalized_advice', models.TextField(blank=True)),
                ('career_plan', models.JSONField(blank=True, default=list)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='orientation.orientationsession')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('series', models.ManyToManyField(blank=True, related_name='subjects', to='orientation.bacserie')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
