# Generated by Django 6.0.6 on 2026-07-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orientation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orientationsession',
            name='mode',
            field=models.CharField(choices=[('CHATBOT', 'Questionnaire'), ('EXPRESS', 'Express (description libre)')], default='CHATBOT', max_length=8),
        ),
        migrations.AddField(
            model_name='orientationsession',
            name='transcript_file',
            field=models.FileField(blank=True, null=True, upload_to='transcripts/'),
        ),
    ]
